package ca.etsmtl.applets.etswebservices.core.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 28/01/2017
//
//---------------------------------------------------



public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
