package ca.etsmtl.applets.etswebservices.directory.soap;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 28/01/2017
//
//---------------------------------------------------


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;

import java.util.List;

import ca.etsmtl.applets.etswebservices.core.soap.Functions;
import ca.etsmtl.applets.etswebservices.core.soap.IServiceEvents;
import ca.etsmtl.applets.etswebservices.core.soap.OperationResult;
import ca.etsmtl.applets.etswebservices.directory.model.ArrayOfFicheEmploye;
import ca.etsmtl.applets.etswebservices.directory.model.ArrayOfFicheEmployeDate;
import ca.etsmtl.applets.etswebservices.directory.model.ArrayOfService;
import ca.etsmtl.applets.etswebservices.directory.model.FicheEmploye;


public class WebServiceSoap
{
    interface IWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="http://etsmtl.ca/cmspages/webservice.asmx";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    IServiceEvents callback;
    public WebServiceSoap(){}

    public WebServiceSoap (IServiceEvents callback)
    {
        this.callback = callback;
    }
    public WebServiceSoap(IServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public WebServiceSoap(IServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected List sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    Object getResult(Class destObj,Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public ArrayOfFicheEmploye Recherche(final String FiltreNom, final String FiltrePrenom, final String FiltreServiceCode ) throws Exception
    {
        return (ArrayOfFicheEmploye)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "Recherche");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="FiltreNom";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FiltreNom!=null?FiltreNom:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="FiltrePrenom";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FiltrePrenom!=null?FiltrePrenom:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="FiltreServiceCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FiltreServiceCode!=null?FiltreServiceCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ArrayOfFicheEmploye)getResult(ArrayOfFicheEmploye.class,__result,"RechercheResult",__envelope);
            }
        },"http://etsmtl.ca/Recherche");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfFicheEmploye>> RechercheAsync(final String FiltreNom,final String FiltrePrenom,final String FiltreServiceCode)
    {
        return executeAsync(new Functions.IFunc< ArrayOfFicheEmploye>() {
            public ArrayOfFicheEmploye Func() throws Exception {
                return Recherche( FiltreNom,FiltrePrenom,FiltreServiceCode);
            }
        });
    }
    
    public ArrayOfFicheEmployeDate RechercheDate(final String FiltreNom, final String FiltrePrenom, final String FiltreServiceCode ) throws Exception
    {
        return (ArrayOfFicheEmployeDate)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "RechercheDate");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="FiltreNom";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FiltreNom!=null?FiltreNom:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="FiltrePrenom";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FiltrePrenom!=null?FiltrePrenom:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="FiltreServiceCode";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(FiltreServiceCode!=null?FiltreServiceCode:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ArrayOfFicheEmployeDate)getResult(ArrayOfFicheEmployeDate.class,__result,"RechercheDateResult",__envelope);
            }
        },"http://etsmtl.ca/RechercheDate");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfFicheEmployeDate>> RechercheDateAsync(final String FiltreNom,final String FiltrePrenom,final String FiltreServiceCode)
    {
        return executeAsync(new Functions.IFunc< ArrayOfFicheEmployeDate>() {
            public ArrayOfFicheEmployeDate Func() throws Exception {
                return RechercheDate( FiltreNom,FiltrePrenom,FiltreServiceCode);
            }
        });
    }
    
    public FicheEmploye GetFicheData(final String Id ) throws Exception
    {
        return (FicheEmploye)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "GetFicheData");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="Id";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Id!=null?Id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (FicheEmploye)getResult(FicheEmploye.class,__result,"GetFicheDataResult",__envelope);
            }
        },"http://etsmtl.ca/GetFicheData");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< FicheEmploye>> GetFicheDataAsync(final String Id)
    {
        return executeAsync(new Functions.IFunc< FicheEmploye>() {
            public FicheEmploye Func() throws Exception {
                return GetFicheData( Id);
            }
        });
    }
    
    public ArrayOfService GetListeDepartement( ) throws Exception
    {
        return (ArrayOfService)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "GetListeDepartement");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ArrayOfService)getResult(ArrayOfService.class,__result,"GetListeDepartementResult",__envelope);
            }
        },"http://etsmtl.ca/GetListeDepartement");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfService>> GetListeDepartementAsync()
    {
        return executeAsync(new Functions.IFunc< ArrayOfService>() {
            public ArrayOfService Func() throws Exception {
                return GetListeDepartement( );
            }
        });
    }
    
    public String GetFiche(final String numero,final String PathFiche ) throws Exception
    {
        return (String)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://etsmtl.ca/", "GetFiche");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="numero";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(numero!=null?numero:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://etsmtl.ca/";
                __info.name="PathFiche";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(PathFiche!=null?PathFiche:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GetFicheResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://etsmtl.ca/GetFiche");
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> GetFicheAsync(final String numero, final String PathFiche)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws Exception {
                return GetFiche( numero,PathFiche);
            }
        });
    }

    
    protected Object execute(IWcfMethod wcfMethod,String methodName) throws Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, OperationResult< T>>  executeAsync(final Functions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {

        return new Exception(fault.faultstring);
    }
}


