package ca.etsmtl.applets.etswebservices.directory.model;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 28/01/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

import ca.etsmtl.applets.etswebservices.core.soap.Helper;
import ca.etsmtl.applets.etswebservices.directory.soap.ExtendedSoapSerializationEnvelope;

public class FicheEmploye extends AttributeContainer implements KvmSerializable
{

    
    public Integer Id=0;
    
    public String Nom;
    
    public String Prenom;
    
    public String TelBureau;
    
    public String Emplacement;
    
    public String Courriel;
    
    public String Service;
    
    public String Titre;
    
    public java.util.Date DateModif;

    public FicheEmploye ()
    {
    }

    public FicheEmploye (Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Id"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Id = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.Id = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Nom"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Nom = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Nom = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Prenom"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Prenom = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Prenom = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("TelBureau"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.TelBureau = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.TelBureau = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Emplacement"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Emplacement = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Emplacement = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Courriel"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Courriel = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Courriel = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Service"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Service = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Service = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Titre"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Titre = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Titre = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("DateModif"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DateModif = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.DateModif = (java.util.Date)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Id;
        }
        if(propertyIndex==1)
        {
            return this.Nom!=null?this.Nom:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Prenom!=null?this.Prenom:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.TelBureau!=null?this.TelBureau:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Emplacement!=null?this.Emplacement:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Courriel!=null?this.Courriel:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.Service!=null?this.Service:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Titre!=null?this.Titre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.DateModif!=null?Helper.getDateTimeFormat().format(this.DateModif):SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 9;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Id";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Nom";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Prenom";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TelBureau";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Emplacement";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Courriel";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Service";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Titre";
            info.namespace= "http://etsmtl.ca/";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateModif";
            info.namespace= "http://etsmtl.ca/";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

